name: Spellcheck

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
            - staging

jobs:
    codespell:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Run codespell
            uses: codespell-project/actions-codespell@v2.0
            with:
              check_filenames: true
              ignore_words_list: crate
              skip: ./.git,./lib,./circuit/Cargo.lock
