name: Foundry

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  test:
    name: Foundry Tests
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Even with deploy key this is needed on the first checkout to tell git to use ssh (??)
      - name: Give GitHub Actions access to axiom-crypto/axiom-eth-working
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.AXIOM_ETH_DEPLOY_PRIVATE_KEY }}
            ${{ secrets.AXIOM_TOOLS_DEPLOY_PRIVATE_KEY }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-01-01
          override: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check forge version
        run: forge --version

      - name: Check forge tree
        run: forge tree

      - name: Run Foundry tests
        run: |
          export PROVIDER_URI_1=${{ secrets.PROVIDER_URI_1 }}
          export PROVIDER_URI_11155111=${{ secrets.PROVIDER_URI_11155111 }}          
          RUST_BACKTRACE=1 forge test -vvv
